### Create order

POST http://localhost:10001/orders
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "user_id": "11d0816b-f71e-409a-b2b9-43a6caac71fa"
}

### Get orders by user id

GET http://localhost:10001/orders?limit=10&offset=0
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get order

GET http://localhost:10001/orders/9a31a7ff-f29e-4c71-a3a7-bed296afeefc
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Add product to order

POST http://localhost:10001/orders/content/9a31a7ff-f29e-4c71-a3a7-bed296afeefc?product_id=b914144a-bc32-41bf-95c7-ed94d2da1704&quantity=2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Delete product from order

DELETE http://localhost:10001/orders/content/9a31a7ff-f29e-4c71-a3a7-bed296afeefc?product_id=b914144a-bc32-41bf-95c7-ed94d2da1704
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Complete order

POST http://localhost:10001/orders/complete/9a31a7ff-f29e-4c71-a3a7-bed296afeefc
Content-Type: application/json
Authorization: Bearer {{auth_token}}