### Update user

PATCH http://localhost:10001/profile
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "old_password": "12345678",
  "new_password": "qaz12345"
}

### Delete user

DELETE http://localhost:10001/profile
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Get user by ID

GET http://localhost:10001/profile
Accept: application/json
Authorization: Bearer {{auth_token}}
