
app:
  is-debug: true
  id: test-task
  name: test-task
  log-level: trace
  migrations-path: file://./migrations

http:
  ip: 0.0.0.0
  port: 10001
  read_timeout: 15s
  write_timeout: 15s

jwt:
  secret: $3cr3t

database:
  type: postgresql
#  dsn: postgresql://postgres:password@db/postgres
  host: 0.0.0.0
  port: 5432
  username: postgres
  password: postgres
  name: postgres
  max_attempts: 5
  connection_timeout: 5s

