BEGIN;

DROP TABLE IF EXISTS orders CASCADE;
-- DROP TABLE IF EXISTS delivery_hours CASCADE;
DROP TABLE IF EXISTS regions CASCADE;
DROP TABLE IF EXISTS couriers CASCADE;
-- DROP TABLE IF EXISTS working_hours CASCADE;
DROP TYPE IF EXISTS courier_type;

END;
